language: node_js
node_js:
  - "11"
  - "10"
  - "8"
  - "6"
before_script:
  - > # node > 10 → lint
    node_version=$(node -v);
    if  [ ${node_version:1:3} = "10." ]; then
      npm run test:lint;
    fi
script: npm run test:unit
addons:
  apt:
    packages:
    - graphicsmagick